// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';


var defaultEmployee = /* record */[/* name */"Default Employee Name"];

exports.defaultEmployee = defaultEmployee;
/* No side effect */
