// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Employee$ReactTemplate = require("./domain/Employee.bs.js");
var EmployeeView$ReactTemplate = require("./EmployeeView.bs.js");

function updateEmployeeName(send, name) {
  return Curry._1(send, /* ChangeName */[name]);
}

var component = ReasonReact.reducerComponent("Store");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return ReasonReact.element(/* None */0, /* None */0, EmployeeView$ReactTemplate.make(self[/* state */1][/* employee */0], (function (newName) {
                                return Curry._1(self[/* send */3], /* ChangeName */[newName]);
                              }), /* array */[]));
            }),
          /* initialState */(function () {
              return /* record */[/* employee */Employee$ReactTemplate.defaultEmployee];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _) {
              return /* Update */Block.__(0, [/* record */[/* employee : record */[/* name */action[0]]]]);
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.updateEmployeeName = updateEmployeeName;
exports.component = component;
exports.make = make;
/* component Not a pure module */
